### ISSUE TITLE
'NoneType' object has no attribute 'attrs'

### ISSUE THREAD

**Issue by sTangtanga** [waugustus/lianjia-spider#1]
main.py", line 16, in <module> data = spy.requestLocale()
spider.py", line 29, in requestLocale  total_page = json.loads(soup.find('div', {'class': 'page-box fr'}).div.attrs['page-data'])['totalPage']
AttributeError: 'NoneType' object has no attribute 'attrs'
这个报错要怎么改呀

**Comment by waugustus** [comment]
麻烦提供一下具体的复现流程

**Comment by sTangtanga** [comment]
安装完依赖库后在前端点抓取数据出现异常，后面在main.py运行也是。
![%7V(Y47(2CP}Y642H$1B7KH](https://github.com/waugustus/lianjia-spider/assets/114153858/bd7210ce-9408-4b24-a4a6-60d2e7deaa78)
![5N54_5DZ12WZF_RAM%T$I6R](https://github.com/waugustus/lianjia-spider/assets/114153858/695f70e7-4893-4397-8bb6-f6aeff571317)

**Comment by waugustus** [comment]
我试了一下没有遇到这个问题，你的config/config.json文件是否有改动

**Comment by sTangtanga** [comment]
我修改了host为重庆市的链接，修改了locale为附近街道名称，我又尝试把locale改为重庆显示list index out of range 我猜是下标超出范围？ 或许是我附近街道没有对应数据？

**Comment by waugustus** [comment]
我试了一下，把host改成如下，没有出现问题

```
{
    "host": "https://cq.lianjia.com",
    "locale": "恒大城",
    "type": "l2l3l4",
    "min_price": 0,
    "max_price": 500
}
```

**Comment by sTangtanga** [comment]
我也按你的输入后还是有问题，好奇怪我没有改其他地方了
![@NRI`(} ``UZW0YTY_LTOUB](https://github.com/waugustus/lianjia-spider/assets/114153858/4b999bd1-21ef-474c-afee-4f6a33de3f9b)

**Comment by waugustus** [comment]
git pull一下

**Comment by sTangtanga** [comment]
好了，我还改了一下进行文件读取的编码方式，非常感谢！！！
